[package]
name = "freight_car_forwarder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
cairo-rs = { version = "0.21.1" , features = ["pdf"] }
pango = "0.21.1"
pango-sys = "0.21.1"
pangocairo = "0.21.1"
rand = "0.9.2"

